---
title: "Project Euler Problems"
output: word_document
---

# Problem 4: Largest Palindrome Product
```{r p-4}
library(dplyr)
library(magrittr)

f2 <- 999
f1 <- c(100:999)
master <- data.frame(f1 = 0, prod = 0, f2 = 0, rev = 0, pal = FALSE)

while(f2 > 99){
  prod  <- f1 * f2
  df    <- cbind(f1, prod) %>% data.frame()
  df$f2 <- f2
  
  df$prod <- as.character(df$prod)
  
  for (i in 1:nrow(df)) {
    df$rev[i] = paste(rev(substring(prod[i],1:nchar(prod[i]),1:nchar(prod[i]))),collapse="")
  }
  
  df <- df %>%
    mutate(pal  = ifelse(prod == rev, TRUE, FALSE),
           prod = as.numeric(prod),
           rev  = as.numeric(rev)) %>%
    filter(pal == TRUE)
  
  master <- rbind(master, df)
  
  f2 = f2 - 1
}

master %>%
  filter(pal == TRUE) %$%
  max(rev)
```

# Problem 3: Largest Prime Factor
```{r p-3}
library(gmp)

factors <- factorize(600851475143)
```

# Problem 2: Even Fibonacci Numbers
```{r p-2}
fib <- c(1, 1)

while (sum(tail(fib, n = 2)) < 4000000) {
  fib <- c(fib, sum(tail(fib, n = 2)))
}

sum <- 0

for (n in fib) {
  if(n %% 2 == 0){
    sum <- sum + n
  }
  sum
}

print(sum)
```

# Problem 1: Multiples of 3 and 5
```{r p-1}
m = 0

for (n in 1:999){
  if(n %% 3 == 0 | n %% 5 == 0){
    m = m + n
  }
}

print(m)
```
