---
output: html_document
---

```{r setup}
# libraries
library(leaflet)
library(stringr)
library(sf)
library(tidyverse)
library(tidycensus)

# census data
census_api_key("api key")

mi_pop <- get_acs(geography = "tract", 
                     variables = c("B17006_001", "B17006_002"), 
                     state = "MI",
                     output = "wide",
                     geometry = TRUE) %>%
  mutate(estimate = B17006_002E/B17006_001E*100) %>%
  filter(!is.na(estimate))

pal <- colorNumeric(palette = "viridis", 
                    domain = mi_pop$estimate)
```

```{r map}
# leaflet map
map <- mi_pop %>%
  st_transform(crs = "+init=epsg:4326") %>%
  leaflet(width = "500", height = "500") %>%
  addProviderTiles(provider = "CartoDB.Positron") %>%
  addPolygons(popup = ~ str_extract(NAME, "^([^,]*)"),
              stroke = FALSE,
              smoothFactor = 0,
              fillOpacity = 0.5,
              color = ~ pal(estimate)) %>%
  addLegend("bottomright", 
            pal = pal, 
            values = ~ estimate,
            title = "% Child Poverty",
            opacity = 1)

# output
map
```

```{r hc}
# highchart
hc <- hchart(mi_pop, 
             "scatter", 
             hcaes(x      = child_pop, 
                   y      = estimate, 
                   size   = child_pov,
                   color  = estimate,
                   county = NAME), 
             name = "County:") %>%
  hc_chart(zoomType = "xy") %>%
  hc_xAxis(title = list(text = "Child Population")) %>%
  hc_yAxis(title = list(text = "% Child Poverty")) %>%
  hc_tooltip(pointFormat = "<b>{point.county}<b>")%>%
  hc_size(width = 600, height = 500)

# output
hc
```
